-- MySQL Script generated by MySQL Workbench
-- mer. 30 mai 2018 18:26:28 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema alamo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alamo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alamo` DEFAULT CHARACTER SET utf8 ;
USE `alamo` ;

-- -----------------------------------------------------
-- Table `alamo`.`booker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alamo`.`booker` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `family_name` VARCHAR(50) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `pseudo` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(250) NULL DEFAULT NULL,
  `phone` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `fav_sport` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alamo`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alamo`.`manager` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `club_name` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(250) NULL DEFAULT NULL,
  `postal_code` INT UNSIGNED NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `lat` FLOAT NULL DEFAULT NULL,
  `lng` FLOAT NULL DEFAULT NULL,
  `mail` VARCHAR(50) NULL DEFAULT NULL,
  `calendar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alamo`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alamo`.`admin` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `password` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alamo`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alamo`.`reservation` (
  `id` INT UNSIGNED NOT NULL,
  `club_id` INT UNSIGNED NULL DEFAULT NULL,
  `calendar_id` INT UNSIGNED NULL DEFAULT NULL,
  `booker_id` INT UNSIGNED NULL,
  `date` DATE NULL,
  `time` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alamo`.`calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alamo`.`calendar` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
